// places.ts — search-alias index. ~1,100 OSM place names (villages/hamlets/suburbs) that aren't
// canonical quarters. Lazy-loaded (NOT in the entry bundle, NOT on first paint) the first time the
// user types in the report search. Each alias resolves to the NEAREST canonical quarter (same as a
// GPS snap) so locals can find their sub-village by name without bloating the 55-quarter list or
// fragmenting the trust pipeline. Generated by data/places/build-aliases.py → web/public/places.json.
export interface Place {
  name: string
  lat: number
  lng: number
  /** macro region id (kanifing/brikama/…), precomputed by point-in-polygon against the real
   *  boundaries. Used as the resolution target when the nearest canonical quarter is too far. */
  r?: string
}

let cache: Promise<Place[]> | null = null

/** Fetch the alias index once (cached). Returns [] on failure — search just falls back to the 55. */
export function loadPlaces(): Promise<Place[]> {
  if (!cache) {
    cache = fetch('/places.json', { headers: { Accept: 'application/json' } })
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => [])
  }
  return cache
}
